# -*- coding: utf-8 -*-
"""DIY Function - Checking the Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrASGUyij9jLLrt7Eg5vBFtFswKXk-8g
"""

#isalpha() Returns True if all characters in the string are in the alphabet
#isdigit() Returns True if all characters in the string are digits
#isalnum() Returns True if all characters in the string are alphanumeric

def isalpha(text):
    c = 0
    for i in text:
        if ((ord(i) >= 65 and ord(i) <= 90) or (ord(i) >= 97 and ord(i) <= 122)):   # (65-90) Upper | (97 - 122) Lower
            c += 1
    if (len(text) == c):
        return True
    else:
        return False

print('Sagpr1r'.isalpha())
print(isalpha('Sagprr'))

def isdigit(text):
    c = 0
    for i in text:
        if (ord(i) >= 48 and ord(i) <= 57):              # (48-57) Digits | 0-9
            c += 1

    if (len(text) == c):
        return True
    else:
        return False

print('12sagprr31'.isdigit())
print(isdigit('1231'))

def isalnum(text):
    c = 0
    for i in text:
        if ((ord(i)>=65 and ord(i)<=90) or (ord(i)>=97 and ord(i)<=122) or (ord(i)>=48 and ord(i)<=57)):
            c += 1
    if (len(text) == c):
        return True
    else:
        return False

print('sagprr14'.isalnum())
print(isalnum('@!$@%#$%'))

